### ISSUE TITLE
import me.bzcoder.easyglide.progress.GlideRequest找不到

### ISSUE THREAD

**Issue by hanqingkai** [BzCoder/EasyGlide#1]
GlideRequest找不到，是没上传还是要特殊处理？
![Q3Y0JIGI)CDQ@ZMJ@L%4K8V](https://user-images.githubusercontent.com/9988660/65734836-68284100-e107-11e9-9ce3-cb2ebdf49eb4.png)

**Comment by BzCoder** [comment]
这个是Glide生成的文件

**Comment by hanqingkai** [comment]
了解，打扰了，告辞
