### ISSUE TITLE
使用中报错

### ISSUE THREAD

**Issue by shengguan** [BzCoder/EasyGlide#2]
![image](https://user-images.githubusercontent.com/8409220/69940881-48a20000-151e-11ea-9a50-2dd628765e51.png)

图片地址：https://image.so.com/view?q=%E7%86%9F%E6%82%89%E7%9A%84%E5%91%B3%E9%81%93%E7%AC%AC%E4%B8%89%E5%AD%A3&src=tab_www&correct=%E7%86%9F%E6%82%89%E7%9A%84%E5%91%B3%E9%81%93%E7%AC%AC%E4%B8%89%E5%AD%A3&ancestor=list&cmsid=036e51e8c876c7ec10dd70143c62c239&cmran=0&cmras=0&cn=0&gn=0&kn=0&fsn=60&adstar=0&clw=255#id=0b26b73db2fdad1d5f180e3850d836b8&currsn=0&ps=58&pc=58

**Comment by shengguan** [comment]
![image](https://user-images.githubusercontent.com/8409220/69940992-8a32ab00-151e-11ea-8db2-06bb082437c5.png)

**Comment by BzCoder** [comment]
图片地址不对，你换成这个试试？
http://o.cztvcloud.com/190/posts/2018/05/21/a718b19cb7b7085f7a7427103c960fb7.jpg?x-oss-process=image/resize,m_fill,h_210,w_300

**Comment by shengguan** [comment]
没报错  但是加载不出来

**Comment by BzCoder** [comment]
但是你发的那个不是一个图片地址啊

**Comment by shengguan** [comment]
我用的你的也加载不出来

**Comment by BzCoder** [comment]
什么报错
